M48
; DRILL file {KiCad (6.0.7)} date Tue Sep 27 00:45:40 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-09-27T00:45:40+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X50.7Y-34.4
T2
X59.7Y-105.4
X72.2Y-105.4
X84.7Y-105.4
T0
M30
