M48
; DRILL file {KiCad (6.0.10)} date Sun Feb 12 23:23:45 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-12T23:23:45+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X40.631Y-26.748
T2
X59.763Y-100.076
X72.263Y-100.076
X84.763Y-100.076
T0
M30
